#!/bin/bash
# prerm script for uninstalling your package
 
set -e
 
# Stop and disable the systemd service
systemctl stop check-device.service
systemctl disable check-device.service
 
# Remove the systemd service file
rm -f /etc/systemd/system/check-device.service
 
# Remove the executable scripts
rm -f /usr/bin/crsf-app
rm -f /usr/bin/check_device.sh
rm -r /usr/usb-bind
 
# Optionally, you can add more cleanup commands here if needed
 
# Exit with status 0 to indicate success
exit 0
